apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghee-app
  namespace: bimal
spec:
  repliacs: 2
  selector:
    matchLabels:
      app: ghee-app
  template:
    metadata:
      labels:
        app: ghee-app
    spec:
      containers:
        - name: cont-1
          image: bimalk074/ghee:v1
          ports:
            - containerPort: 5656