version: '3.8'

services:
  app:
    image: organic-ghee:v1
    container_name: organic-ghee-app
    ports:
      - "5656:5656"
    environment:
      - MONGO_URL=mongodb://mongo:27017/restorent
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
